---

- name: Configure Raspberry Pi Cluser
  hosts: raspberry-pi-cluster
  become: true
  vars:
    pi_home: /home/pi
  roles:
    - role: common
    - role: openssl-keys
    - role: golang
    - role: mpi

- name: Configure Hadoop master nodes
  hosts: hadoop-master-nodes
  vars:
    java_home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt
    hadoop_home: /home/pi/hadoop
    hadoop_version: 2.9.0
  roles:
    - role: hadoop-common
    - role: hadoop-master-nodes

- name: Configure Hadoop slave nodes
  hosts: hadoop-slave-nodes
  vars:
    java_home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt
    hadoop_home: /home/pi/hadoop
    hadoop_version: 2.9.0
  roles:
    - role: hadoop-common
    - role: hadoop-slave-nodes
