---

- name: generate an OpenSSL private key with the default values (4096 bits, RSA)
  openssl_privatekey:
    path: /home/pi/.ssh/{{ ansible_ssh_name }}_key
    owner: pi
    group: pi

- name: generate an OpenSSL public key
  openssl_publickey:
    path: /home/pi/.ssh/{{ ansible_ssh_name }}_key.pub
    privatekey_path: /home/pi/.ssh/{{ ansible_ssh_name }}_key
    format: OpenSSH
    owner: pi
    group: pi

- name: update user .bashrc
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK FOR THE COMMON ROLE ###"
    block: "{{ lookup('file', './files/user.bashrc') }}"
    dest: /home/pi/.bashrc

- name: update root .bashrc
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK FOR THE COMMON ROLE ###"
    block: "{{ lookup('file', './files/root.bashrc') }}"
    dest: /root/.bashrc

- name: update /etc/hosts
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: "{{ lookup('file', './files/hosts') }}"
    dest: /etc/hosts

- name: install development packages
  apt: name=build-essential
       state=latest
