---

- name: update user .bashrc
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK FOR THE COMMON ROLE ###"
    block: "{{ lookup('file', './files/user.bashrc') }}"
    dest: /home/pi/.bashrc

- name: update root .bashrc
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK FOR THE COMMON ROLE ###"
    block: "{{ lookup('file', './files/root.bashrc') }}"
    dest: /root/.bashrc

- name: update /etc/hosts
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: "{{ lookup('file', './files/hosts') }}"
    dest: /etc/hosts

- name: install development packages
  apt: name=build-essential
       state=latest
